name: Lint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

permissions:
  checks: write
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run format:check || (echo "Prettier found formatting issues. Please run 'npm run format' locally to fix them." && exit 1)
        
      - name: Run ESLint
        run: npm run lint